### ISSUE TITLE
How to get the extrinsic parameters between left rgb and left thr?

### ISSUE THREAD

**Issue by JialeiXu** [UkcheolShin/MS2-MultiSpectralStereoDataset#2]
Thank you for your work！
According to your code:
ext_NIR2THR = np.concatenate([calib['R_nir2thr'], calib['T_nir2thr']*0.001], axis=1) # mm -> m scale conversion.
ext_NIR2RGB = np.concatenate([calib['R_nir2rgb'], calib['T_nir2rgb']*0.001], axis=1)
ext_THR2NIR = np.linalg.inv(np.concatenate([ext_NIR2THR, [[0,0,0,1]]],axis=0))
ext_THR2RGB = np.matmul(np.concatenate([ext_NIR2RGB, [[0,0,0, 1]]],axis=0), ext_THR2NIR)
ext_RGB2NIR = np.linalg.inv(np.concatenate([ext_NIR2RGB, [[0,0,0,1]]],axis=0))
ext_RGB2THR = np.linalg.inv(ext_THR2RGB)

I get the ext_RGB2THR,  can it express extrinsic parameters from  left rgb to left thr?

**Comment by UkcheolShin** [comment]
Yes, it indicates the extrinsic parameter from left RGB to left thermal camera.

**Comment by JialeiXu** [comment]
Thanks
