### ISSUE TITLE
Upload dataset on google drive

### ISSUE THREAD

**Issue by casiatao** [UkcheolShin/MS2-MultiSpectralStereoDataset#6]
Could you upload the dataset to Google Drive, please? There is some trouble when downloading the dataset vis Dropbox.  Thank you very much!

**Comment by UkcheolShin** [comment]
Hello, I initially considered Google Drive, but Google Drive has a narrow bandwidth that makes it hard to distribute datasets to many people. So, I decided to use Dropbox. Recently, there have been lots of dataset downloading and they seem fine. Could you provide more details of your trouble case, such as an error message or picture, to let me check it out?

**Comment by casiatao** [comment]
Sorry for my late reply. It seems that I can not get access to the Dropbox website through command lines. But I can access it through the browser.
